server:
  port: 8083

spring:
  application:
    name: analytics-service

transaction:
  base-url: lb://transaction-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
