server:
  port: 8761

spring:
  application:
    name: service-discovery

# 디스커버리 서버 자신은 다른 곳에 등록하지 않습니다.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
